export const metadata = {
    title: 'User',
    description: 'Generated by create next app',
  }

export default function Layout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <div>{children}<div>Navigate to Top</div></div>
    )
}
  